version: '3'

services:
  # survey:
  #   build: survey_server/
  #   depends_on:
  #     - 'database'
  #   ports: 
  #     - '8080:8080'

  api:
    build: api/
    # depends_on:
    #   - 'database'
    ports:
      - '3001:3001'
    volumes:
      - ./api:/src/app
      - /src/app/node_modules


  #  db:
  #   image: postgres
  #   restart: always
  #   environment:
  #     POSTGRES_PASSWORD: example

  # database:
  #   image: mongo:latest
